### ISSUE TITLE
Recursive relations

### ISSUE THREAD

**Issue by maxgronlund** [LoggableActivity/LoggableActivity#43]
As it is not there is only one level in relations, consider this example
```
Demo::Club: 
  record_display_name: email 
  route: demo_club/:id
  loggable_attrs: 
    - email
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :address
      model: Demo::Address
      route: address/:id
      loggable_attrs:
        - street

```
It would be nice is it was possible to dive deeper in to the relations, so if the address belongs to a city it could be included like this
```
Demo::Club: 
  record_display_name: email 
  route: demo_club/:id
  loggable_attrs: 
    - email
  auto_log:
    - create
    - update
    - destroy
  relations:
    - belongs_to: :address
      model: Demo::Address
      route: address/:id
      loggable_attrs:
        - street
        relations: <<--- FROM HERE
           - belongs_do: city
            model: Demo::City
            loggable_attrs:
              - name
```
