### ISSUE TITLE
Mark fields so they are not deleted

### ISSUE THREAD

**Issue by maxgronlund** [LoggableActivity/LoggableActivity#44]
When the data owner are deleted, all field in the log are no longer asseccible.
It whoud be nice if it was possible to store a list of public attributes.

```
Demo::Club: 
  record_display_name: email 
  route: demo_club/:id
  loggable_attrs: 
    - email
  auto_log:
    - create
    - update
    - destroy
   keep_after_destroy:
    - age
```
